# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /nfs/ug/homes-1/t/tramblei/vivaldo_fresh_eth_xadc_fft_dma_corr/vivaldo_fresh_eth_xadc_fft_dma_corr.srcs/sources_1/bd/design_1/ip/design_1_geralds_correlation_wrapper_0_0/design_1_geralds_correlation_wrapper_0_0.xci
# IP: The module: 'design_1_geralds_correlation_wrapper_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /nfs/ug/homes-1/t/tramblei/vivaldo_fresh_eth_xadc_fft_dma_corr/vivaldo_fresh_eth_xadc_fft_dma_corr.srcs/sources_1/bd/design_1/ip/design_1_geralds_correlation_wrapper_0_0/src/corr_wrapper_div_gen_0_0/corr_wrapper_div_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==corr_wrapper_div_gen_0_0 || ORIG_REF_NAME==corr_wrapper_div_gen_0_0}]

# IP: /nfs/ug/homes-1/t/tramblei/vivaldo_fresh_eth_xadc_fft_dma_corr/vivaldo_fresh_eth_xadc_fft_dma_corr.srcs/sources_1/bd/design_1/ip/design_1_geralds_correlation_wrapper_0_0/src/corr_wrapper_projection_correlation_calculator_v1_0_0_1/corr_wrapper_projection_correlation_calculator_v1_0_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==corr_wrapper_projection_correlation_calculator_v1_0_0_1 || ORIG_REF_NAME==corr_wrapper_projection_correlation_calculator_v1_0_0_1}]

# IP: /nfs/ug/homes-1/t/tramblei/vivaldo_fresh_eth_xadc_fft_dma_corr/vivaldo_fresh_eth_xadc_fft_dma_corr.srcs/sources_1/bd/design_1/ip/design_1_geralds_correlation_wrapper_0_0/src/corr_wrapper_mult_gen_0_0/corr_wrapper_mult_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==corr_wrapper_mult_gen_0_0 || ORIG_REF_NAME==corr_wrapper_mult_gen_0_0}]

# IP: /nfs/ug/homes-1/t/tramblei/vivaldo_fresh_eth_xadc_fft_dma_corr/vivaldo_fresh_eth_xadc_fft_dma_corr.srcs/sources_1/bd/design_1/ip/design_1_geralds_correlation_wrapper_0_0/src/corr_wrapper_xlslice_0_0/corr_wrapper_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==corr_wrapper_xlslice_0_0 || ORIG_REF_NAME==corr_wrapper_xlslice_0_0}]

# IP: /nfs/ug/homes-1/t/tramblei/vivaldo_fresh_eth_xadc_fft_dma_corr/vivaldo_fresh_eth_xadc_fft_dma_corr.srcs/sources_1/bd/design_1/ip/design_1_geralds_correlation_wrapper_0_0/src/corr_wrapper_c_shift_ram_0_0/corr_wrapper_c_shift_ram_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==corr_wrapper_c_shift_ram_0_0 || ORIG_REF_NAME==corr_wrapper_c_shift_ram_0_0}]

# IP: /nfs/ug/homes-1/t/tramblei/vivaldo_fresh_eth_xadc_fft_dma_corr/vivaldo_fresh_eth_xadc_fft_dma_corr.srcs/sources_1/bd/design_1/ip/design_1_geralds_correlation_wrapper_0_0/src/corr_wrapper_util_vector_logic_0_0/corr_wrapper_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==corr_wrapper_util_vector_logic_0_0 || ORIG_REF_NAME==corr_wrapper_util_vector_logic_0_0}]

# IP: /nfs/ug/homes-1/t/tramblei/vivaldo_fresh_eth_xadc_fft_dma_corr/vivaldo_fresh_eth_xadc_fft_dma_corr.srcs/sources_1/bd/design_1/ip/design_1_geralds_correlation_wrapper_0_0/src/corr_wrapper_xlconcat_0_0/corr_wrapper_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==corr_wrapper_xlconcat_0_0 || ORIG_REF_NAME==corr_wrapper_xlconcat_0_0}]

# IP: /nfs/ug/homes-1/t/tramblei/vivaldo_fresh_eth_xadc_fft_dma_corr/vivaldo_fresh_eth_xadc_fft_dma_corr.srcs/sources_1/bd/design_1/ip/design_1_geralds_correlation_wrapper_0_0/src/corr_wrapper_xlconstant_0_0/corr_wrapper_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==corr_wrapper_xlconstant_0_0 || ORIG_REF_NAME==corr_wrapper_xlconstant_0_0}]

# IP: /nfs/ug/homes-1/t/tramblei/vivaldo_fresh_eth_xadc_fft_dma_corr/vivaldo_fresh_eth_xadc_fft_dma_corr.srcs/sources_1/bd/design_1/ip/design_1_geralds_correlation_wrapper_0_0/src/corr_wrapper_cordic_0_2/corr_wrapper_cordic_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==corr_wrapper_cordic_0_2 || ORIG_REF_NAME==corr_wrapper_cordic_0_2}]

# IP: /nfs/ug/homes-1/t/tramblei/vivaldo_fresh_eth_xadc_fft_dma_corr/vivaldo_fresh_eth_xadc_fft_dma_corr.srcs/sources_1/bd/design_1/ip/design_1_geralds_correlation_wrapper_0_0/src/corr_wrapper_cordic_2_0/corr_wrapper_cordic_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==corr_wrapper_cordic_2_0 || ORIG_REF_NAME==corr_wrapper_cordic_2_0}]

# IP: /nfs/ug/homes-1/t/tramblei/vivaldo_fresh_eth_xadc_fft_dma_corr/vivaldo_fresh_eth_xadc_fft_dma_corr.srcs/sources_1/bd/design_1/ip/design_1_geralds_correlation_wrapper_0_0/src/corr_wrapper_util_vector_logic_1_0/corr_wrapper_util_vector_logic_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==corr_wrapper_util_vector_logic_1_0 || ORIG_REF_NAME==corr_wrapper_util_vector_logic_1_0}]

# IP: /nfs/ug/homes-1/t/tramblei/vivaldo_fresh_eth_xadc_fft_dma_corr/vivaldo_fresh_eth_xadc_fft_dma_corr.srcs/sources_1/bd/design_1/ip/design_1_geralds_correlation_wrapper_0_0/src/corr_wrapper_c_shift_ram_1_0/corr_wrapper_c_shift_ram_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==corr_wrapper_c_shift_ram_1_0 || ORIG_REF_NAME==corr_wrapper_c_shift_ram_1_0}]

# IP: /nfs/ug/homes-1/t/tramblei/vivaldo_fresh_eth_xadc_fft_dma_corr/vivaldo_fresh_eth_xadc_fft_dma_corr.srcs/sources_1/bd/design_1/ip/design_1_geralds_correlation_wrapper_0_0/src/corr_wrapper_util_vector_logic_2_0/corr_wrapper_util_vector_logic_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==corr_wrapper_util_vector_logic_2_0 || ORIG_REF_NAME==corr_wrapper_util_vector_logic_2_0}]

# IP: /nfs/ug/homes-1/t/tramblei/vivaldo_fresh_eth_xadc_fft_dma_corr/vivaldo_fresh_eth_xadc_fft_dma_corr.srcs/sources_1/bd/design_1/ip/design_1_geralds_correlation_wrapper_0_0/src/corr_wrapper_util_vector_logic_2_1/corr_wrapper_util_vector_logic_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==corr_wrapper_util_vector_logic_2_1 || ORIG_REF_NAME==corr_wrapper_util_vector_logic_2_1}]

# IP: /nfs/ug/homes-1/t/tramblei/vivaldo_fresh_eth_xadc_fft_dma_corr/vivaldo_fresh_eth_xadc_fft_dma_corr.srcs/sources_1/bd/design_1/ip/design_1_geralds_correlation_wrapper_0_0/src/corr_wrapper_c_shift_ram_2_1/corr_wrapper_c_shift_ram_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==corr_wrapper_c_shift_ram_2_1 || ORIG_REF_NAME==corr_wrapper_c_shift_ram_2_1}]

# XDC: /nfs/ug/homes-1/t/tramblei/vivaldo_fresh_eth_xadc_fft_dma_corr/vivaldo_fresh_eth_xadc_fft_dma_corr.srcs/sources_1/bd/design_1/ip/design_1_geralds_correlation_wrapper_0_0/src/corr_wrapper_ooc.xdc

# IP: /nfs/ug/homes-1/t/tramblei/vivaldo_fresh_eth_xadc_fft_dma_corr/vivaldo_fresh_eth_xadc_fft_dma_corr.srcs/sources_1/bd/design_1/ip/design_1_geralds_correlation_wrapper_0_0/design_1_geralds_correlation_wrapper_0_0.xci
# IP: The module: 'design_1_geralds_correlation_wrapper_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /nfs/ug/homes-1/t/tramblei/vivaldo_fresh_eth_xadc_fft_dma_corr/vivaldo_fresh_eth_xadc_fft_dma_corr.srcs/sources_1/bd/design_1/ip/design_1_geralds_correlation_wrapper_0_0/src/corr_wrapper_div_gen_0_0/corr_wrapper_div_gen_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==corr_wrapper_div_gen_0_0 || ORIG_REF_NAME==corr_wrapper_div_gen_0_0}]

# IP: /nfs/ug/homes-1/t/tramblei/vivaldo_fresh_eth_xadc_fft_dma_corr/vivaldo_fresh_eth_xadc_fft_dma_corr.srcs/sources_1/bd/design_1/ip/design_1_geralds_correlation_wrapper_0_0/src/corr_wrapper_projection_correlation_calculator_v1_0_0_1/corr_wrapper_projection_correlation_calculator_v1_0_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==corr_wrapper_projection_correlation_calculator_v1_0_0_1 || ORIG_REF_NAME==corr_wrapper_projection_correlation_calculator_v1_0_0_1}]

# IP: /nfs/ug/homes-1/t/tramblei/vivaldo_fresh_eth_xadc_fft_dma_corr/vivaldo_fresh_eth_xadc_fft_dma_corr.srcs/sources_1/bd/design_1/ip/design_1_geralds_correlation_wrapper_0_0/src/corr_wrapper_mult_gen_0_0/corr_wrapper_mult_gen_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==corr_wrapper_mult_gen_0_0 || ORIG_REF_NAME==corr_wrapper_mult_gen_0_0}]

# IP: /nfs/ug/homes-1/t/tramblei/vivaldo_fresh_eth_xadc_fft_dma_corr/vivaldo_fresh_eth_xadc_fft_dma_corr.srcs/sources_1/bd/design_1/ip/design_1_geralds_correlation_wrapper_0_0/src/corr_wrapper_xlslice_0_0/corr_wrapper_xlslice_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==corr_wrapper_xlslice_0_0 || ORIG_REF_NAME==corr_wrapper_xlslice_0_0}]

# IP: /nfs/ug/homes-1/t/tramblei/vivaldo_fresh_eth_xadc_fft_dma_corr/vivaldo_fresh_eth_xadc_fft_dma_corr.srcs/sources_1/bd/design_1/ip/design_1_geralds_correlation_wrapper_0_0/src/corr_wrapper_c_shift_ram_0_0/corr_wrapper_c_shift_ram_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==corr_wrapper_c_shift_ram_0_0 || ORIG_REF_NAME==corr_wrapper_c_shift_ram_0_0}]

# IP: /nfs/ug/homes-1/t/tramblei/vivaldo_fresh_eth_xadc_fft_dma_corr/vivaldo_fresh_eth_xadc_fft_dma_corr.srcs/sources_1/bd/design_1/ip/design_1_geralds_correlation_wrapper_0_0/src/corr_wrapper_util_vector_logic_0_0/corr_wrapper_util_vector_logic_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==corr_wrapper_util_vector_logic_0_0 || ORIG_REF_NAME==corr_wrapper_util_vector_logic_0_0}]

# IP: /nfs/ug/homes-1/t/tramblei/vivaldo_fresh_eth_xadc_fft_dma_corr/vivaldo_fresh_eth_xadc_fft_dma_corr.srcs/sources_1/bd/design_1/ip/design_1_geralds_correlation_wrapper_0_0/src/corr_wrapper_xlconcat_0_0/corr_wrapper_xlconcat_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==corr_wrapper_xlconcat_0_0 || ORIG_REF_NAME==corr_wrapper_xlconcat_0_0}]

# IP: /nfs/ug/homes-1/t/tramblei/vivaldo_fresh_eth_xadc_fft_dma_corr/vivaldo_fresh_eth_xadc_fft_dma_corr.srcs/sources_1/bd/design_1/ip/design_1_geralds_correlation_wrapper_0_0/src/corr_wrapper_xlconstant_0_0/corr_wrapper_xlconstant_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==corr_wrapper_xlconstant_0_0 || ORIG_REF_NAME==corr_wrapper_xlconstant_0_0}]

# IP: /nfs/ug/homes-1/t/tramblei/vivaldo_fresh_eth_xadc_fft_dma_corr/vivaldo_fresh_eth_xadc_fft_dma_corr.srcs/sources_1/bd/design_1/ip/design_1_geralds_correlation_wrapper_0_0/src/corr_wrapper_cordic_0_2/corr_wrapper_cordic_0_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==corr_wrapper_cordic_0_2 || ORIG_REF_NAME==corr_wrapper_cordic_0_2}]

# IP: /nfs/ug/homes-1/t/tramblei/vivaldo_fresh_eth_xadc_fft_dma_corr/vivaldo_fresh_eth_xadc_fft_dma_corr.srcs/sources_1/bd/design_1/ip/design_1_geralds_correlation_wrapper_0_0/src/corr_wrapper_cordic_2_0/corr_wrapper_cordic_2_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==corr_wrapper_cordic_2_0 || ORIG_REF_NAME==corr_wrapper_cordic_2_0}]

# IP: /nfs/ug/homes-1/t/tramblei/vivaldo_fresh_eth_xadc_fft_dma_corr/vivaldo_fresh_eth_xadc_fft_dma_corr.srcs/sources_1/bd/design_1/ip/design_1_geralds_correlation_wrapper_0_0/src/corr_wrapper_util_vector_logic_1_0/corr_wrapper_util_vector_logic_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==corr_wrapper_util_vector_logic_1_0 || ORIG_REF_NAME==corr_wrapper_util_vector_logic_1_0}]

# IP: /nfs/ug/homes-1/t/tramblei/vivaldo_fresh_eth_xadc_fft_dma_corr/vivaldo_fresh_eth_xadc_fft_dma_corr.srcs/sources_1/bd/design_1/ip/design_1_geralds_correlation_wrapper_0_0/src/corr_wrapper_c_shift_ram_1_0/corr_wrapper_c_shift_ram_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==corr_wrapper_c_shift_ram_1_0 || ORIG_REF_NAME==corr_wrapper_c_shift_ram_1_0}]

# IP: /nfs/ug/homes-1/t/tramblei/vivaldo_fresh_eth_xadc_fft_dma_corr/vivaldo_fresh_eth_xadc_fft_dma_corr.srcs/sources_1/bd/design_1/ip/design_1_geralds_correlation_wrapper_0_0/src/corr_wrapper_util_vector_logic_2_0/corr_wrapper_util_vector_logic_2_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==corr_wrapper_util_vector_logic_2_0 || ORIG_REF_NAME==corr_wrapper_util_vector_logic_2_0}]

# IP: /nfs/ug/homes-1/t/tramblei/vivaldo_fresh_eth_xadc_fft_dma_corr/vivaldo_fresh_eth_xadc_fft_dma_corr.srcs/sources_1/bd/design_1/ip/design_1_geralds_correlation_wrapper_0_0/src/corr_wrapper_util_vector_logic_2_1/corr_wrapper_util_vector_logic_2_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==corr_wrapper_util_vector_logic_2_1 || ORIG_REF_NAME==corr_wrapper_util_vector_logic_2_1}]

# IP: /nfs/ug/homes-1/t/tramblei/vivaldo_fresh_eth_xadc_fft_dma_corr/vivaldo_fresh_eth_xadc_fft_dma_corr.srcs/sources_1/bd/design_1/ip/design_1_geralds_correlation_wrapper_0_0/src/corr_wrapper_c_shift_ram_2_1/corr_wrapper_c_shift_ram_2_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==corr_wrapper_c_shift_ram_2_1 || ORIG_REF_NAME==corr_wrapper_c_shift_ram_2_1}]

# XDC: /nfs/ug/homes-1/t/tramblei/vivaldo_fresh_eth_xadc_fft_dma_corr/vivaldo_fresh_eth_xadc_fft_dma_corr.srcs/sources_1/bd/design_1/ip/design_1_geralds_correlation_wrapper_0_0/src/corr_wrapper_ooc.xdc
